TOP = ../..
include $(TOP)/configure/CONFIG
#ARCH = win32-x86
#TARGETS += envPaths dllPath.bat
#ARCH = windows-x64
#TARGETS += envPaths dllPath.bat
ARCH = linux-x86
TARGETS += envPaths
#ARCH = linux-x86_64
#TARGETS += envPaths
include $(TOP)/configure/RULES.ioc

